export const FIELD_TYPE_OPTIONS = [
  {
    value: "TEXT",
    labelId: "additional.fieldTypes.text",
    defaultMessage: "Text",
  },
  {
    value: "TEXTAREA",
    labelId: "additional.fieldTypes.textarea",
    defaultMessage: "Long text",
  },
  {
    value: "NUMBER",
    labelId: "additional.fieldTypes.number",
    defaultMessage: "Number",
  },
  {
    value: "DATE",
    labelId: "additional.fieldTypes.date",
    defaultMessage: "Date",
  },
  {
    value: "TIME",
    labelId: "additional.fieldTypes.time",
    defaultMessage: "Time",
  },
  {
    value: "DATETIME",
    labelId: "additional.fieldTypes.datetime",
    defaultMessage: "Date and time",
  },
  {
    value: "BOOLEAN",
    labelId: "additional.fieldTypes.boolean",
    defaultMessage: "Checkbox",
  },
  {
    value: "SELECT",
    labelId: "additional.fieldTypes.select",
    defaultMessage: "Select",
  },
  {
    value: "MULTISELECT",
    labelId: "additional.fieldTypes.multiselect",
    defaultMessage: "Multiple select",
  },
  {
    value: "RADIO",
    labelId: "additional.fieldTypes.radio",
    defaultMessage: "Radio buttons",
  },
  {
    value: "DOCUMENT",
    labelId: "additional.fieldTypes.document",
    defaultMessage: "Document",
  },
  {
    value: "USER",
    labelId: "additional.fieldTypes.user",
    defaultMessage: "User",
  },
];

export const OPTION_FIELD_TYPES = new Set(["SELECT", "MULTISELECT", "RADIO"]);

export const toCodeCandidate = (value = "") =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_");

export const createEmptyOption = (sortOrder = 1) => ({
  optionKey: "",
  optionLabel: "",
  active: true,
  sortOrder,
  isAutoGeneratedKey: true,
  isNew: true,
});

export const normalizeOptionForUi = (option = {}, index = 0) => {
  const optionLabel = (option.optionLabel || "").trim();
  const generatedKey = toCodeCandidate(optionLabel);
  const rawOptionKey = (option.optionKey || "").trim();
  const optionKey = rawOptionKey || generatedKey;

  return {
    id: option.id ?? undefined,
    optionKey,
    optionLabel,
    active: option.active !== false,
    sortOrder: option.sortOrder ?? index + 1,
    isAutoGeneratedKey: !rawOptionKey || rawOptionKey === generatedKey,
    isNew: option.id == null,
  };
};

export const normalizeOptionsForPayload = (options = []) =>
  options
    .map((option, index) => {
      const normalizedKey = option?.isAutoGeneratedKey
        ? toCodeCandidate(option?.optionLabel || "")
        : toCodeCandidate(option?.optionKey || option?.optionLabel || "");

      return {
        id: option?.id ?? undefined,
        optionKey: normalizedKey,
        optionLabel: (option?.optionLabel || "").trim(),
        active: option?.active !== false,
        sortOrder: index + 1,
      };
    })
    .filter((option) => option.optionKey && option.optionLabel);

export const getAdditionalFieldTypeLabel = (intl, fieldType) => {
  const option = FIELD_TYPE_OPTIONS.find(
    ({ value }) => value === String(fieldType || "").toUpperCase(),
  );

  if (!option) {
    return fieldType || "";
  }

  return intl.formatMessage({
    id: option.labelId,
    defaultMessage: option.defaultMessage,
  });
};
